### ISSUE TITLE
error connecting to /tmp/tmux-1001/default (No such file or directory)

### ISSUE THREAD

**Issue by ikamensh** [openai/universe-starter-agent#108]
Anyone has ideas why I get this error and what exactly it means?

```
(universe-starter-agent) ikamenshchikov@olympia-zen:~/universe-starter-agent$ python 
train.py --num-workers 2 --env-id PongDeterministic-v3 --log-dir /tmp/pong
Executing the following commands:
mkdir -p /tmp/pong
echo /home/ikamenshchikov/anaconda/envs/universe-starter-agent/bin/python train.py --
num-workers 2 --env-id PongDeterministic-v3 --log-dir /tmp/pong > /tmp/pong/cmd.sh
kill $( lsof -i:12345 -t ) > /dev/null 2>&1
kill $( lsof -i:12222-12224 -t ) > /dev/null 2>&1
tmux kill-session -t a3c
tmux new-session -s a3c -n ps -d bash
tmux new-window -t a3c -n w-0 bash
tmux new-window -t a3c -n w-1 bash
tmux new-window -t a3c -n tb bash
tmux new-window -t a3c -n htop bash
sleep 1
tmux send-keys -t a3c:ps 'CUDA_VISIBLE_DEVICES= /home/ikamenshchikov/anaconda/envs/un
iverse-starter-agent/bin/python worker.py --log-dir /tmp/pong --env-id PongDeterminis
tic-v3 --num-workers 2 --job-name ps' Enter
tmux send-keys -t a3c:w-0 'CUDA_VISIBLE_DEVICES= /home/ikamenshchikov/anaconda/envs/u
niverse-starter-agent/bin/python worker.py --log-dir /tmp/pong --env-id PongDetermini
stic-v3 --num-workers 2 --job-name worker --task 0 --remotes 1' Enter
tmux send-keys -t a3c:w-1 'CUDA_VISIBLE_DEVICES= /home/ikamenshchikov/anaconda/envs/u
niverse-starter-agent/bin/python worker.py --log-dir /tmp/pong --env-id PongDetermini
stic-v3 --num-workers 2 --job-name worker --task 1 --remotes 1' Enter
tmux send-keys -t a3c:tb 'tensorboard --logdir /tmp/pong --port 12345' Enter
tmux send-keys -t a3c:htop htop Enter
**error connecting to /tmp/tmux-1001/default (No such file or directory)**
Use `tmux attach -t a3c` to watch process output
Use `tmux kill-session -t a3c` to kill the job
Point your browser to http://localhost:12345 to see Tensorboard
(universe-starter-agent)
```

**Comment by ikamensh** [comment]
This appears to be just the typical message when error occurs in worker process (in my case import error)

**Comment by AbstractMonkey** [comment]
If you don't mind, how did you fix this? I am getting the same error.

**Comment by ikamensh** [comment]
This is not the actual error, its just a hint that there might be an error (seems to be also sometimes caused by parallel processes, even if all errors are fixed.)
Go to tmux and then to worker process (tmux -a -> Ctrl-B -> 1(number uncertain, see on the bottom of the screen)), there you might see the actual problem message.

**Comment by EMCP** [comment]
in this case : 

```
~/Dev/git/openai/universe-starter-agent$ CUDA_VISIBLE_DEVICES= /usr/bin/python3 worker.py --log-dir /tmp/pong --env-id PongDeterministic-v3 --num-workers 2 --job-name worker --task 0 --remotes 1
Traceback (most recent call last):
  File "worker.py", line 2, in <module>
    import cv2
ImportError: No module named 'cv2'

```

**Comment by kevinkicho** [comment]
Hi, could you advise? here are my messages.
(0) ps-
`kevin@kevinmalverns:~/Documents/universe-starter-agent$ CUDA_VISIBLE_DEVICES= /home/kevin/anaconda2/envs/universe-starter-agent/bin/python3 worker.py --log-dir /tmp/pong --env-id PongDeterministic-v4 --num-workers 2 --job-name ps
Traceback (most recent call last):
  File "worker.py", line 3, in <module>
    import go_vncdriver
ImportError: No module named 'go_vncdriver'
`
(1) w-0
`kevin@kevinmalverns:~/Documents/universe-starter-agent$ CUDA_VISIBLE_DEVICES= /home/kevin/anaconda2/envs/universe-starter-agent/bin/python3 worker.py --log-dir /tmp/pong --env-id PongDeterministic-v4 --num-workers 2 --job-name worker --task 0 --remotes 1
Traceback (most recent call last):
  File "worker.py", line 3, in <module>
    import go_vncdriver
ImportError: No module named 'go_vncdriver'`
(2) w-1
`kevin@kevinmalverns:~/Documents/universe-starter-agent$ CUDA_VISIBLE_DEVICES= /home/kevin/anaconda2/envs/universe-starter-agent/bin/python3 worker.py --log-dir /tmp/pong --env-id PongDeterministic-v4 --num-workers 2 --job-name worker --task 1 --remotes 1
Traceback (most recent call last):
  File "worker.py", line 3, in <module>
    import go_vncdriver
ImportError: No module named 'go_vncdriver'
`
(3) tb
'kevin@kevinmalverns:~/Documents/universe-starter-agent$ tensorboard --logdir /tmp/pong --port 12345
TensorBoard 0.1.8 at http://kevinmalverns:12345 (Press CTRL+C to quit)
'
This weird, because I already have fixed this problem before.  I am running OpenAI_Game_Bot_Live_stream <https://github.com/llSourcell/OpenAI_Game_Bot_Live_stream> fine. Thanks for your attention on this.

**Comment by EMCP** [comment]
read the error message and you will see

`ìmport govnc`

you need to install goVNC as per instructions found here https://github.com/openai/go-vncdriver
