### ISSUE TITLE
The NeonRace example is not learning

### ISSUE THREAD

**Issue by futurely** [openai/universe-starter-agent#42]
To solve the tmux problem as described in https://github.com/openai/universe-starter-agent/issues/2, the  example was run in different shell windows with the following commands.

CUDA_VISIBLE_DEVICES= /usr/bin/python worker.py --log-dir /tmp/neonrace --env-id flashgames.NeonRace-v0 --num-workers 2 --job-name ps

CUDA_VISIBLE_DEVICES= /usr/bin/python worker.py --log-dir /tmp/neonrace --env-id flashgames.NeonRace-v0 --num-workers 2 --job-name worker --task 0 --remotes 1

CUDA_VISIBLE_DEVICES= /usr/bin/python worker.py --log-dir /tmp/neonrace --env-id flashgames.NeonRace-v0 --num-workers 2 --job-name worker --task 1 --remotes 1

tensorboard --logdir /tmp/neonrace --port 12345

The agents seemed to be doing nothing and the TensorBoard was empty.

![image](https://cloud.githubusercontent.com/assets/9004594/21652700/c2b06204-d2e8-11e6-83e9-5debbc3096b6.png)

OS: Ubuntu 16.04

TensorFlow: 0.12.1

universe.flashgames: 0.20.21

**Comment by tlbtlbtlb** [comment]
I reproduced your steps, and it works on my machine. Maybe I didn't understand something you're doing. Linked is a screen capture from running same commands you gave, using Python 3.5, tensorflow 0.12.1 and universe.flashgames 0.20.21 (but on OSX). You can see the car driving, badly (because it hasn't learned anything yet) and tensorboard shows results. It takes hours before it learns to stay on the road.

Screen capture: https://www.youtube.com/watch?v=jFxmNhdwUD4

Can you be more specific about what seems to be going wrong on your system?

**Comment by futurely** [comment]
Thanks for your instructions! I downgraded TensorFlow to 0.11.0 CPU only version and cleaned up the /tmp/* log dirs, then the above commands finally run as expected. The worker processes failed to connect with the parameter server process using the latest TensorFlow.
