### ISSUE TITLE
Multi-Discrete Action Space

### ISSUE THREAD

**Issue by bzier** [openai/universe-starter-agent#75]
I am attempting to adapt this agent to work with a custom gym/universe environment I'm building. The action space of my environment uses a `MultiDiscrete` space. This starter agent explicitly references `env.action_space.n` from the `Discrete` space which doesn't exist on a `MultiDiscrete` object. I am able to change those references to `env.action_space.shape` instead, but that breaks for `Discrete` spaces, and, more significantly in my case, it results in the agent choosing a single action from the MultiDiscrete space to 'max out' with these calls:
```python
value = tf.squeeze(tf.multinomial(logits - tf.reduce_max(logits, [1], keep_dims=True), 1), [1])
tf.one_hot(value, d)
[...]
env.step(action.argmax())
```
My action space looks like this:
```python
self.action_space = spaces.MultiDiscrete([[-80, 80],
                                          [-80, 80],
                                          [0, 1],
                                          [0, 1],
                                          [0, 1]])
```
The agent chooses an action like `[0. 0. 0. 0. 1.]` or `[0. 1. 0. 0. 0.]`. I would like it to choose an action from within the action space such as `[74. -52. 0. 1. 0.]`.

Does anyone have any suggestions as to how I can accommodate this? Ultimately, I think it would be best to build support for all the types of `Space` since it seems the idea is to abstract away environment details from the agent anyway. I'm new to Gym, Universe and Tensorflow and really ML in general, so any help you can offer would be much appreciated. Thanks.

**Comment by M00NSH0T** [comment]
I don't know if anything was ever sorted out with this or not, but I tried using the MultiDiscrete space in a similar way to what was described above as well and was unsuccessful.  Honestly, just trying to figure out how to properly use the MultiDiscrete action space within my step function was a bit of a mess.  I switched over to the Tuple type, with two Discrete spaces inside... much simpler to use and seems to work as intended.  If you're still stuck (I know this was a long time ago), but maybe try it out.

The algorithmic environment offers an example of how to initialize and use this.  Look here:
https://github.com/openai/gym/blob/master/gym/envs/algorithmic/algorithmic_env.py

I was unable to find a similar example with multidiscrete.  Be great if somebody could build up the documentation on all this a bit more for those of us looking to get involved.  Unless you want to just play Atari games or Go, it's hard figuring out where to begin with building your own custom environment, which is a shame because Reinforcement Learning obviously has far reaching applications beyond just building better gaming bots.  The fundamental space types could use some more documentation.  Like why do I need to set bounds on my observation space variables?  What if I don't want there to be an 'edge of the board' so to speak?  Like if I'm using function approximators instead of tables.  Maybe there's a reason, I just can't figure it out...

**Comment by aymen-mouelhi** [comment]
@bzier any updates on this plz? I am working on your mupen64plus env and I'm having the same issue with the actions spaces

**Comment by M00NSH0T** [comment]
I'm sure there's a more 'correct' way to do it, but for my application, I've just given up entirely on using both multi-discrete or tuple action spaces.  I instead just use a normal discrete space with tons of discrete actions, each representing the combination of what would have been my multi-discrete variables.  It's a pain, but it works at least.  None of the libraries I've found online really work with multi-discrete action spaces for the same reason bzier pointed out.  I recommend that if you actually want to get something working sooner rather than later, you try just translating those combined action states into a single action vector.  Mine has over 1500 as a results, which is annoying, but workable.  Also, if you're using a large action space set, check out the Wolpertinger algorithm developed by DeepMind.  jimkon has built a repo that gets like 95% the way to implementing it... just needs some work for it to work with discrete spaces.  But it's supposed to work much, much better for large discrete spaces than anything else out there. I hope more implementations for it come out soon.

**Comment by aymen-mouelhi** [comment]
@M00NSH0T this exactly the way I'm implementing it right now, and the least I can say it is not the most "correct" way to do it. Thanks for pointing me to the Wolpertinger algorithm, I will take a look on that.

**Comment by M00NSH0T** [comment]
@aymen-mouelhi yeah far from the most elegant / ideal way to do it.  It's really clunky... each time I try to whittle down my action space to try to speed up the training, I have to redo a bunch of if/else logic.  If you find a better solution, could you post it here? 

Also, one other thing I did that seems to have helped a lot in my application, which was inspired by something I read in the paper about the Wolp algo, was action filtering.  This too is something that isn't really built into OpenAI the way I think it needs to be (unless I'm just missing it... I am still learning). I added a function to my own custom openai environment that basically spits out a vector of ones and zeros each timestep to say whether a particular action is valid or not.  I then use that to zero out the Q values for invalid actions before my agent makes a choice, but obviously it would be more computationally efficient if there was a more embedded way of doing this that just prevented those actions from having q values calculated for them in the first place.  I may go back and try to get implemented, but it would require a lot more effort than my quick and dirty solution there. Still, it saves a ton of time in training large action spaces because at least you don't waste resources exploring invalid actions.  My previous approach was to penalize invalid actions, but that only partially worked. Constraining my system to only explore valid actions in the first place has made a huge difference.

Anyway, good luck.

**Comment by bzier** [comment]
@aymen-mouelhi I never worked out the multi-discrete action space issues. Like @M00NSH0T, I ended up implementing a discrete space, but in my case I only used a dozen of so actions, rather than coming up with all the possible permutations.
See here for the implementation: https://github.com/bzier/gym-mupen64plus/blob/3551409db59ccba1912c004c1612b2b1aa2ecc8d/gym_mupen64plus/envs/MarioKart64/discrete_envs.py#L5

I have been able to successfully train an RL agent using an adapted version of this code, along with some changes to my environment. I still need to clean up some things, write up some documentation, and merge the code. But I can at least point you to what I have at the moment (just be aware it's not done yet).

Environment changes are here: https://github.com/bzier/gym-mupen64plus/pull/38

Agent tweaks are here:
https://github.com/bzier/universe-starter-agent/tree/mario-kart-agent

Be aware that the agent changes are also based on changes to run everything in docker containers. You can find those changes in the 'dockerize' branch here:
https://github.com/bzier/gym-mupen64plus/tree/dockerize

Like I mentioned, I need to do some work still to pull this all together and make setup easier and clearer. If you have any questions, or bump into any problems related to that, feel free to open an issue on that repo. It will make the conversation a little easier to track and reduce clutter here.

If anyone ends up figuring out the true multi-discrete problem, absolutely comment here.

**Comment by aymen-mouelhi** [comment]
@bzier Thank you very much for your very detailed answer (and links) ! I will try your implementation and try to check how it works and then hopefully some pull requests will start coming :)

**Comment by rdevulap** [comment]
Similar problem: 

This code: 
`self.action_space = spaces.Tuple(
            [spaces.Discrete(3), spaces.Discrete(10)]
            )`
gave this error:   
`num_actions=env.action_space.n,
AttributeError: 'Tuple' object has no attribute 'n'`

and this: 

`self.action_space = spaces.MultiDiscrete([3,10])`

gave this error: 

`  self.low = np.array([x[0] for x in array_of_param_array])
TypeError: 'int' object is not subscriptable`
