### ISSUE TITLE
Any possible to use GPU and make it faster

### ISSUE THREAD

**Issue by syhdog** [openai/universe-starter-agent#76]
The project is great and I am very appreciate it. But it still not implement on GPU, and I would if modify some lines in the code should make it work with GPU and make is faster. I have a tensorflow GPU ready platform and tensorflow 1.0 (well, I have made a few unimportant change to the code so that it works fine with tensorflow 1.0).
Again, thanks a lot for opening this project, it's been a great contribution.

**Comment by yaroslavvb** [comment]
The issue is that architecture size and training procedure (many forward props with batch size 1) makes it hard to benefit from a GPU.

I've experimented a bit with it, and found that it needs a big refactoring to make it worth it (ie, running 16 environments together and batching 16 forward props).

Note, when running with GPU version you must set the following variable
`export OPENCV_OPENCL_RUNTIME=`

**Comment by nczempin** [comment]
The A3C algorithm that's being used here has recently been extended to a hybrid CPU/GPU approach, see [this repo](https://github.com/NVlabs/GA3C) and [this paper](https://arxiv.org/pdf/1611.06256.pdf).
